GET http://localhost:3000

###
POST http://localhost:3000/insertItems
Content-Type: application/json

{
        "title": "Teste Item 02",
		"description": "Este é o terceiro item",
		"value": 250,
		"status": "active"
}


###
GET http://localhost:3000/listItems?search=20
Content-Type: application/json


###
PUT http://localhost:3000/Items/02ae7d41-c082-4e4c-920a-a7b3a2d60bee
Content-Type: application/json

{
        "title": "Item numero 20",
		"description": "Este foi o ultimo item",
		"value": 1000,
		"status": "inactive"
}


###
DELETE http://localhost:3000/Items/3e9dd267-138e-4cc4-ba54-43bab4ee224a

